import Head from "next/head";
import { useRouter } from "next/router";
import { api } from "../utils/api";
import Spinner from "../components/Spinner";

const Crawler = () => {
  //Get the query param from the URL
  const router = useRouter();
  const { query } = router.query;

  const { data, isLoading } = api.crawler.get.useQuery(
    {
      query: query as string,
    },
    {
      enabled: !!query && query != "",
      refetchOnWindowFocus: false,
    }
  );

  !!data && console.log(data.html?.a[10]);

  if (isLoading) {
    return (
      <div className="flex min-h-screen w-full items-center justify-center bg-gradient-to-b from-orange-800 to-red-800">
        <Spinner />
      </div>
    );
  }
  return (
    <>
      <Head>
        <title>Crawling</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css"
          integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w=="
          crossOrigin="anonymous"
          referrerPolicy="no-referrer"
        />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-orange-800 to-red-800">
        <button
          onClick={() => router.push("/")}
          className="absolute left-8 top-6 flex items-center text-slate-200 outline-none transition-colors hover:text-white"
        >
          <i className="fa-solid fa-angles-left text-xl" />
        </button>
        {!!data && data.error !== null && (
          <h1 className="text-xl text-slate-200">{data.error}</h1>
        )}
        {!!data && data.html !== null && (
          <div>
            {data.html.a.map((anchor) => {
              return <p className="text-slate-200">{anchor}</p>;
            })}
          </div>
        )}
      </main>
    </>
  );
};

export default Crawler;
